[package]
name = "quinco"
version = "0.0.3"
description = "A Tauri App"
authors = ["shichen437"]
edition = "2021"

[lib]
name = "quinco_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2.7.3"
tauri-plugin-fs = "2.5.2"
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
tauri-plugin-updater = "2.11.0"
async-trait = "0.1"
bytes = "1.5"
chrono = { version = "0.4", features = ["serde"] }
futures-util = "0.3"
genai = "0.7.0-beta"
pin-project = "1.1"
reqwest = { version = "0.13", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
aes = "0.8"
cbc = { version = "0.1", features = ["alloc", "block-padding"] }
pbkdf2 = "0.12"
rand = "0.8"
sqlx = { version = "0.8", features = ["sqlite", "runtime-tokio-rustls", "migrate", "chrono"] }
sys-locale = "0.3"
tokio = { version = "1", features = ["full"] }
toml = "0.8"
tracing = "0.1"
uuid = { version = "1", features = ["v4"] }
